# Azure Pipeline that runs basic continuous integration on a Terraform project

trigger:
  branches:
    include:
      - naftest
  paths:
    include:
      - /naftest

resources:
  repositories:
    - repository: modules
      type: git
      name: "modules"

variables:
  azureLocation: 'us-west-3'
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)'
  terraformVersion: $(latest)

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
      - job: TerraformContinuousIntegrationJob
        displayName: TerraformContinuousIntegration - CI Job
        pool:
          vmImage: ubuntu-20.04
        steps:
          - checkout: modules

          # Authenticate to modules repository using PAT
          - script: git config --global url."https://$(PAT_TOKEN)@dev.azure.com/".insteadOf "https://dev.azure.com/"
            displayName: 'Authenticate with PAT'
            env: 
              PAT_TOKEN: $(PatToken)

          # Pass necessary environment variables to Terraform commands
          - task: TerraformCLI@0
            displayName: 'Run terraform init'
            inputs:
              command: init
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceName: $(serviceConnection1)
              terraformVersion: $(latest)
              backendConfig: '-backend-config="access_key=$(SecretKey)"'
            env:
              ARM_SUBSCRIPTION_ID: $(subscriptionId)
              ARM_TENANT_ID: $(tenantId)

          # Run Terraform validate
          - task: TerraformCLI@0
            displayName: 'Run terraform validate'
            inputs:
              command: validate
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceName: $(serviceConnection1)
              terraformVersion: $(latest)

          # Verify module files with Checkov
          - bash: checkov --directory $(System.DefaultWorkingDirectory)
            displayName: 'Verify modules with Checkov'

          # Run Terraform plan
          - task: TerraformCLI@0
            displayName: 'Run terraform plan'
            inputs:
              command: plan
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceName: $(serviceConnection1)
              terraformVersion: $(latest)

          # Run Terraform apply
          - task: TerraformCLI@0
            displayName: 'Run terraform apply'
            inputs:
              command: apply
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceName: $(serviceConnection1)
              terraformVersion: $(latest)

        env:
          PAT_TOKEN: $(PatToken)
          SecretKey: $(KeyVaultSecret)

resources:
  variables:
    SecretKey: $(KeyVaultSecret)
